fos_elastica:
    clients:
        default: { host: '%elastica_host%', port: '%elastica_port%', logger: true }
    indexes:
        app:
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer:
                                type: custom
                                tokenizer: nGram
                                filter:  [lowercase, snowball]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 3
                                max_gram: 10
                        filter:
                            snowball:
                                type: snowball
                                language: English
            types:
                set:
                    mappings:
                        id: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                        name: { analyzer: custom_analyzer, search_analyzer: "standard" }
                        year: { type: integer }
                        partCount: { type: integer }
                        theme:
                            type: "object"
                            properties:
                                id: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                                name: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Rebrickable\Set
                        provider: ~
                        finder: ~
                        repository: AppBundle\Repository\Search\SetRepository
                model:
                    mappings:
                        id: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                        name: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                        aliases:
                            type: "object"
                            properties:
                                id: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                        category:
                            type: "object"
                            properties:
                                id: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                                name: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                        keywords:
                            type: "object"
                            properties:
                                name: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\LDraw\Model
                        provider: ~
                        finder: ~
                        repository: AppBundle\Repository\Search\ModelRepository