fos_elastica:
    clients:
        default: { host: '%elastica_host%', port: '%elastica_port%', logger: true }
    indexes:
        app:
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer:
                                type: custom
                                tokenizer: nGram
                                filter:  [lowercase,stopwords]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 3
                                max_gram: 20
                        filter:
                            snowball:
                                type: snowball
                                language: English
                            stopwords:
                                type:      stop
                                stopwords: [_english_]
                                ignore_case : true
            types:
                set:
                    mappings:
                        id: ~
                        name: { analyzer: custom_analyzer, search_analyzer: "standard" }
                        year: { type: integer }
                        partCount: { type: integer }
                        theme:
                            type: "object"
                            properties:
                                id: ~
                                name: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Rebrickable\Set
                        provider: ~
                        finder: ~
                        repository: AppBundle\Repository\Search\SetRepository
                model:
                    mappings:
                        id: ~
                        name: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                        aliases:
                            type: "object"
                            properties:
                                id: ~
                        category:
                            type: "object"
                            properties:
                                id: ~
                                name: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                        keywords:
                            type: "object"
                            properties:
                                name: { analyzer: custom_analyzer, search_analyzer: "standard"  }
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\LDraw\Model
                        provider: ~
                        finder: ~
                        repository: AppBundle\Repository\Search\ModelRepository