liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        set_min:
              quality: 90
              data_loader: set_image_loader
              cache: ~
              default_image: "/resources/images/noimage_min.png"
              filters:
                  thumbnail: { size: [200, 200], mode: inset }
                  background: { size: [250, 250], position: center, color: '#FFFFFF' }
        set_large:
              data_loader: set_image_loader
              cache: ~
              quality: 90
              default_image: "/resources/images/noimage_large.png"
              filters:
                  thumbnail: { size: [840, 580], mode: inset }
                  background: { size: [900, 600], position: center, color: '#FFFFFF' }
        part_min:
              quality: 90
              data_loader: part_image_loader
              cache: ~
              default_image: "/resources/images/noimage_min.png"
              filters:
                  thumbnail: { size: [200, 200], mode: inset }
                  background: { size: [250, 250], position: center, color: '#FFFFFF' }
        part_large:
              data_loader: part_image_loader
              cache: ~
              quality: 90
              default_image: "/resources/images/noimage_large.png"
              filters:
                  thumbnail: { size: [840, 580], mode: inset }
                  background: { size: [900, 600], position: center, color: '#FFFFFF' }
