services:
    client.brickset:
        class: AppBundle\Client\Brickset\Brickset
        arguments: ['%brickset_apikey%']
    client.rebrickable:
        class: AppBundle\Client\Rebrickable\Rebrickable
        arguments: ['%rebrickable_apikey%']
    app.collection_service:
        class: AppBundle\Service\CollectionService
        arguments: ['@client.brickset','@client.rebrickable']
    app.form.filter_set:
        class: AppBundle\Form\FilterSetType
        arguments: ['@app.collection_service']
        tags:
            - { name: form.type }