services:
    client.brickset:
        class: AppBundle\Api\Client\Brickset\Brickset
        arguments: ['%brickset_apikey%']
    client.rebrickable:
        class: AppBundle\Api\Client\Rebrickable\Rebrickable
        arguments: ['%rebrickable_apikey%']

    manager.brickset:
        class: AppBundle\Api\Manager\BricksetManager
        arguments: ['@client.brickset']
    manager.rebrickable:
          class: AppBundle\Api\Manager\RebrickableManager
          arguments: ['@client.rebrickable']

    sevice.collection:
        class: AppBundle\Service\CollectionService
        arguments: ['@doctrine.orm.entity_manager', '@manager.brickset','@manager.rebrickable']

    loader.rebrickable:
        class: AppBundle\Loader\RebrickableLoader
        arguments: ['@doctrine.orm.entity_manager', '@manager.rebrickable']
    loader.ldraw:
        class: AppBundle\Loader\LDrawLoader
        arguments: ['@doctrine.orm.entity_manager', '%kernel.root_dir%/../bin/ldview', '@oneup_flysystem.ldraw_filesystem']
  
    app.form.filter_set:
        class: AppBundle\Form\FilterSetType
        arguments: ['@manager.brickset']
        tags:
            - { name: form.type }