services:
    api.client.brickset:
        class: AppBundle\Api\Client\Brickset\Brickset
        arguments: ['%brickset_apikey%']
    api.client.rebrickable:
        class: AppBundle\Api\Client\Rebrickable\Rebrickable_v3
        arguments: ['%rebrickable_apikey%']

    api.manager.brickset:
        class: AppBundle\Api\Manager\BricksetManager
        arguments: ['@api.client.brickset']
    api.manager.rebrickable:
        class: AppBundle\Api\Manager\RebrickableManager
        arguments: ['@api.client.rebrickable']