services:
    client.brickset:
        class: AppBundle\Api\Client\Brickset\Brickset
        arguments: ['%brickset_apikey%']
    client.rebrickable:
        class: AppBundle\Api\Client\Rebrickable\Rebrickable_v3
        arguments: ['%rebrickable_apikey%']

    manager.brickset:
        class: AppBundle\Api\Manager\BricksetManager
        arguments: ['@client.brickset']
    manager.rebrickable:
        class: AppBundle\Api\Manager\RebrickableManager
        arguments: ['@client.rebrickable']