services:
    api.client.brickset:
        class: AppBundle\Api\Client\Brickset\Brickset
        arguments: ['%brickset_apikey%', '%kernel.root_dir%/config/brickset.xml']
    api.client.rebrickable:
        class: AppBundle\Api\Client\Rebrickable\Rebrickable_v3
        arguments: ['%rebrickable_apikey%']

    api.manager.brickset:
        class: AppBundle\Api\Manager\BricksetManager
        arguments: ['@api.client.brickset', '@app.brickset.cache_provider']
    api.manager.rebrickable:
        class: AppBundle\Api\Manager\RebrickableManager
        arguments: ['@api.client.rebrickable']