services:
    form.filter.brickset:
        class: AppBundle\Form\FilterSetType
        arguments: ['@api.manager.brickset']
        tags:
            - { name: form.type }

    form.search.model:
        class: AppBundle\Form\Search\ModelSearchType
        arguments:
            - '@repository.ldraw.category'
        tags:
            - { name: form.type }

    form.search.set:
        class: AppBundle\Form\Search\SetSearchType
        arguments:
            - '@repository.rebrickable.theme'
            - '@repository.rebrickable.set'
        tags:
            - { name: form.type }
