services:
    service.loader.base:
        abstract:  true
        class: AppBundle\Service\Loader\BaseLoader
        calls:
          - [setArguments, ['@doctrine.orm.entity_manager', '@monolog.logger.loader']]

    service.ldview:
        class: AppBundle\Service\LDViewService
        arguments: ['%ldview_bin%', '@oneup_flysystem.media_filesystem']

    service.loader.rebrickable:
        class: AppBundle\Service\Loader\RebrickableLoader
        arguments: ['%rebrickable_csv_url%']
        parent: service.loader.base

    service.loader.model:
        class: AppBundle\Service\Loader\ModelLoader
        arguments: ['@service.ldview', '@app.relation.mapper']
        parent: service.loader.base

    service.loader.relation:
        class: AppBundle\Service\Loader\RelationLoader
        arguments: ['@api.manager.rebrickable', '@app.relation.mapper']
        parent: service.loader.base