services:
    service.loader:
        abstract:  true
        class: AppBundle\Service\Loader\BaseLoaderService
        calls:
          - [setArguments, ['@doctrine.orm.entity_manager', '@app.relation.mapper']]

    service.ldview:
        class: AppBundle\Service\LDViewService
        arguments: ['%ldview_bin%', '@oneup_flysystem.media_filesystem']

    loader.rebrickable:
        class: AppBundle\Loader\RebrickableLoader
        calls:
          - [setArguments, ['@manager.rebrickable', '%rebrickable_url%']]
        parent: service.loader

    util.dat.parser:
        class: AppBundle\Utils\DatParser
        arguments: ['@app.relation.mapper']

    service.loader.ldraw:
        class: AppBundle\Service\Loader\LDrawLoaderService
        arguments: ['@service.ldview', '%ldraw_url%', '@manager.ldraw', '@util.dat.parser']
        parent: service.loader
