services:
    service.loader.base:
        abstract:  true
        class: AppBundle\Service\Loader\BaseLoader
        calls:
          - [setArguments, ['@doctrine.orm.entity_manager', '@monolog.logger.loader', '@app.transformer.format']]

    service.loader.rebrickable:
        class: AppBundle\Service\Loader\RebrickableLoader
        arguments: ['%app.rebrickable_downloads_url%']
        parent: service.loader.base

    service.loader.model:
        class: AppBundle\Service\Loader\ModelLoader
        arguments: ['@service.stl.converter', '@app.relation.mapper']
        parent: service.loader.base

    service.loader.relation:
        class: AppBundle\Service\Loader\RelationLoader
        arguments: ['@app.relation.mapper','@repository.ldraw.model', '@repository.rebrickable.part']
        parent: service.loader.base

    service.loader.image:
        class: AppBundle\Service\Loader\ImageLoader
        arguments: ['@oneup_flysystem.media_filesystem', '%app.rebrickable_downloads_url%','@service.stl.renderer']
        parent: service.loader.base