services:
    service.loader:
        abstract:  true
        class: AppBundle\Service\Loader\BaseLoaderService
        calls:
          - [setArguments, ['@doctrine.orm.entity_manager', '@app.relation.mapper']]

    service.ldview:
        class: AppBundle\Service\LDViewService
        arguments: ['%ldview_bin%', '@oneup_flysystem.media_filesystem', '@oneup_flysystem.ldraw_library_filesystem']

    service.loader.rebrickable:
        class: AppBundle\Service\Loader\RebrickableLoaderService
        arguments: ['%rebrickable_url%']
        parent: service.loader

    service.loader.ldraw:
        class: AppBundle\Service\Loader\LDrawLoaderService
        arguments: ['@oneup_flysystem.ldraw_library_filesystem','@service.ldview', '@manager.ldraw', '@app.relation.mapper']
        parent: service.loader

    service.loader.relation:
        class: AppBundle\Service\Loader\RelationLoader
        arguments: ['@manager.ldraw.model', '@repository.rebrickable.part', '@api.manager.rebrickable']
        parent: service.loader