services:
    local.manager.base:
        abstract:  true
        class: AppBundle\Manager\BaseManager
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]

    local.manager.rebrickable:
        class: AppBundle\Manager\RebrickableManager
        parent: local.manager.base

    manager.ldraw.keyword:
        class: AppBundle\Manager\LDraw\KeywordManager
        arguments:
            - "@repository.ldraw.keyword"
    manager.ldraw.category:
        class: AppBundle\Manager\LDraw\CategoryManager
        arguments:
            - "@repository.ldraw.category"
    manager.ldraw.subpart:
        class: AppBundle\Manager\LDraw\SubpartManager
        arguments:
            - "@repository.ldraw.subpart"
    manager.ldraw.model:
        class: AppBundle\Manager\LDraw\ModelManager
        arguments:
            - "@repository.ldraw.model"
    manager.ldraw.alias:
        class: AppBundle\Manager\LDraw\AliasManager
        arguments:
            - "@repository.ldraw.alias"

