services:
    manager.ldraw.keyword:
        class: AppBundle\Manager\LDraw\KeywordManager
        arguments:
            - "@repository.ldraw.keyword"
    manager.ldraw.category:
        class: AppBundle\Manager\LDraw\CategoryManager
        arguments:
            - "@repository.ldraw.category"
    manager.ldraw.type:
        class: AppBundle\Manager\LDraw\TypeManager
        arguments:
            - "@repository.ldraw.type"
    manager.ldraw.subpart:
        class: AppBundle\Manager\LDraw\SubpartManager
        arguments:
            - "@repository.ldraw.subpart"
    manager.ldraw.model:
        class: AppBundle\Manager\LDraw\ModelManager
        arguments:
            - "@repository.ldraw.model"
    manager.ldraw.alias:
        class: AppBundle\Manager\LDraw\AliasManager
        arguments:
            - "@repository.ldraw.alias"



