services:
    manager.ldraw.keyword:
        class: AppBundle\Manager\LDraw\KeywordManager
        arguments:
            - "@repository.ldraw.keyword"
    manager.ldraw.category:
        class: AppBundle\Manager\LDraw\CategoryManager
        arguments:
            - "@repository.ldraw.category"
    manager.ldraw.type:
        class: AppBundle\Manager\LDraw\TypeManager
        arguments:
            - "@repository.ldraw.type"
    manager.ldraw.part:
        class: AppBundle\Manager\LDraw\PartManager
        arguments:
            - "@repository.ldraw.part"
    manager.ldraw.partRelation:
        class: AppBundle\Manager\LDraw\Part_RelationManager
        arguments:
            - "@repository.ldraw.partRelation"


