services:
    menu.builder.main:
        class: AppBundle\Menu\Builder
        arguments: ['@knp_menu.factory', '@request_stack']
        tags:
        - { name: knp_menu.menu_builder, method: mainMenu, alias: mainMenu }