services:
    repository.ldraw.keyword:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\LDraw\Keyword

    repository.ldraw.category:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\LDraw\Category

    repository.ldraw.model:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\LDraw\Model

    repository.ldraw.part:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\LDraw\Part

    repository.ldraw.type:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\LDraw\Type

    repository.ldraw.subpart:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\LDraw\Subpart

    repository.ldraw.alias:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\LDraw\Alias

    repository.ldraw.author:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine", getRepository]
            arguments:
                - AppBundle\Entity\LDraw\Author


    repository.rebrickable.category:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\Rebrickable\Category

    repository.rebrickable.color:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\Rebrickable\Color

    repository.rebrickable.inventory:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\Rebrickable\Inventory

    repository.rebrickable.inventoryPart:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\Rebrickable\Inventory_Part

    repository.rebrickable.part:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\Rebrickable\Part

    repository.rebrickable.set:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine", getRepository]
          arguments:
              - AppBundle\Entity\Rebrickable\Set

    repository.rebrickable.theme:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine", getRepository]
            arguments:
                - AppBundle\Entity\Rebrickable\Theme