services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments: ['@api.manager.rebrickable']
        tags:
            - { name: twig.extension }

    app.relation.mapper:
        class: AppBundle\Utils\RelationMapper
        arguments:
            - ['%kernel.root_dir%/Resources/relations']

    service.renderer.stl:
        class: AppBundle\Service\StlRendererService
        arguments: ['%kernel.root_dir%/Resources/povray_layout/layout.tmpl', '%povray_bin%','%stl2pov_bin%']

    service.ldview:
        class: AppBundle\Service\LDViewService
        arguments: ['%ldview_bin%', '@oneup_flysystem.media_filesystem']
