services:
    sevice.collection:
        class: AppBundle\Service\CollectionService
        arguments: ['@doctrine', '@manager.brickset','@manager.rebrickable']

    service.ldraw:
        class: AppBundle\Service\LDrawService
        arguments:
            - '@manager.ldraw.category'
            - '@manager.ldraw.keyword'
            - '@manager.ldraw.type'
            - '@manager.ldraw.part'
            - '@manager.ldraw.partRelation'

    app.form.filter_set:
        class: AppBundle\Form\FilterSetType
        arguments: ['@manager.brickset']
        tags:
            - { name: form.type }