services:
    manager.ldraw:
        class: AppBundle\Manager\LDrawManager
        arguments:
            - '@manager.ldraw.category'
            - '@manager.ldraw.keyword'
            - '@manager.ldraw.type'
            - '@manager.ldraw.subpart'
            - '@manager.ldraw.model'
            - '@manager.ldraw.alias'

    app.form.filter_set:
        class: AppBundle\Form\FilterSetType
        arguments: ['@manager.brickset']
        tags:
            - { name: form.type }    app.relation.mapper:
    app.relation.mapper:
        class: AppBundle\Utils\RelationMapper
        arguments:
            - ['%kernel.root_dir%/Resources/relations']