services:
    app.brickset.cache_provider:
          class: Doctrine\Common\Cache\PhpFileCache
          arguments: ["%kernel.cache_dir%/brickset", ".cache.php"]

    service.renderer.stl:
        class: AppBundle\Service\StlRendererService
        arguments: ['%kernel.root_dir%/Resources/povray_layout/layout.tmpl', '%povray_bin%','%stl2pov_bin%']

    service.ldview:
        class: AppBundle\Service\LDViewService
        arguments: ['%ldview_bin%', '@oneup_flysystem.media_filesystem']

    service.set:
        class: AppBundle\Service\SetService
        arguments: ['@repository.rebrickable.inventorypart']