services:
    app.brickset.cache_provider:
          class: Doctrine\Common\Cache\PhpFileCache
          arguments: ["%kernel.cache_dir%/brickset", ".cache.php"]

    service.stl.renderer:
        class: AppBundle\Service\Stl\StlRendererService
        arguments: ['%kernel.root_dir%/Resources/povray_layout/layout.tmpl', '%povray_bin%','%stl2pov_bin%']

    service.stl.converter:
        class: AppBundle\Service\Stl\StlConverterService
        arguments: ['%ldview_bin%', '@oneup_flysystem.media_filesystem', '@service.stl.fixer']

    service.stl.fixer:
        class: AppBundle\Service\Stl\StlFixerService
        arguments: ['%admesh_bin%']

    service.zip:
          class: AppBundle\Service\ZipService
          arguments: ['@oneup_flysystem.media_filesystem', '@service.set']

    service.set:
        class: AppBundle\Service\SetService
        arguments: ['@repository.rebrickable.inventorypart']        arguments: ['@repository.rebrickable.inventorypart']    app.part_image_loader:
    app.part_image_loader:
        class: AppBundle\Imagine\PartImageLoader
        arguments: ['@api.manager.rebrickable', '@oneup_flysystem.media_filesystem']
        tags:
            - { name: liip_imagine.binary.loader, loader: part_image_loader }