services:
    app.transformer.format:
        class: AppBundle\Transformer\FormatTransformer

    app.relation.mapper:
        class: AppBundle\Util\RelationMapper
        calls:
            - [ loadResource, ['%kernel.root_dir%/Resources/relations/part_model.yml', 'part_model']]
            - [ loadResource, ['%kernel.root_dir%/Resources/relations/alias_model.yml', 'alias_model']]

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments: ['@app.transformer.format']
        tags:
            - { name: twig.extension }